name = "org.boredos.doomgeneric"
version = "1.0.0"
description = "DOOMgeneric port for Nova"
author = "BoredOS Community"
license = "GPLv3"

[install]
bin = "/bin"
assets = "/Library/AppData/org.boredos.doomgeneric"
